In [16]:
import tensorflow as tf

In [17]:
tensor = tf.ones([2,2,3])
print(tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
reshaped_tensor = tf.reshape(tensor, [1,3,4]) # one 3 by 4 matrice
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 3, 4), dtype=float32)


In [ ]:
reshaped_tensor = tf.reshape(tensor, [12]) #Linear
print(reshaped_tensor)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(12,), dtype=float32)
